# Generated by Django 3.0.3 on 2020-03-03 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tile',
        ),
    ]
