# Generated by Django 3.0.4 on 2020-03-04 22:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_directions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='room',
            name='targets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=None),
        ),
    ]
