# Generated by Django 3.0.4 on 2020-03-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200304_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='biome',
            field=models.CharField(default='Grass lands', max_length=25),
        ),
    ]
