# Generated by Django 3.0.3 on 2020-03-03 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_tile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tile',
        ),
    ]
