# Generated by Django 3.0.3 on 2020-03-03 22:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_room_tiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tiles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=100),
        ),
    ]
