# Generated by Django 3.0.3 on 2020-03-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0006_auto_20200303_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='tiles',
        ),
    ]
