# Generated by Django 3.0.3 on 2020-03-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0008_auto_20200304_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=0)),
                ('direction', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='e_to',
        ),
        migrations.RemoveField(
            model_name='room',
            name='n_to',
        ),
        migrations.RemoveField(
            model_name='room',
            name='s_to',
        ),
        migrations.RemoveField(
            model_name='room',
            name='w_to',
        ),
    ]
