# Generated by Django 3.0.3 on 2020-03-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0009_auto_20200304_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='connections',
            field=models.ManyToManyField(to='adventure.Connection'),
        ),
    ]
